sudo: required

language: go

services:
  - docker

go:
  - 1.7.x

install:
  - go get github.com/constabulary/gb/...
  - go get github.com/TIBCOSoftware/flogo-cli/...

script:
  - flogo create WeatherApp
  - cp getWeather.json ./WeatherApp
  - cd WeatherApp
  - flogo add activity github.com/TIBCOSoftware/flogo-contrib/activity/log
  - flogo add activity github.com/TIBCOSoftware/flogo-contrib/activity/rest
  - flogo add activity github.com/TIBCOSoftware/flogo-contrib/activity/reply
  - flogo add trigger github.com/TIBCOSoftware/flogo-contrib/trigger/rest
  - flogo add flow getWeather.json
  - cp ../triggers.json ./bin
  - flogo build
  - cd ..

after_script:
  - docker build -t flogo/getweather:1.0 .
  - docker images
