sudo: required

language: go

services:
  - docker

go:
  - 1.7.x

install:
  - go get github.com/constabulary/gb/...
  - go get github.com/TIBCOSoftware/flogo-cli/...

script:
  - flogo create WeatherApp
  - cp app/getWeather.json ./WeatherApp
  - cd WeatherApp
  - flogo add activity github.com/TIBCOSoftware/flogo-contrib/activity/log
  - flogo add activity github.com/TIBCOSoftware/flogo-contrib/activity/rest
  - flogo add activity github.com/TIBCOSoftware/flogo-contrib/activity/reply
  - flogo add trigger github.com/TIBCOSoftware/flogo-contrib/trigger/rest
  - flogo add flow getWeather.json
  - cp ../app/triggers.json ./bin
  - flogo build

after_script:
  - docker build -t mellistibco/weatherapp:latest ../
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mellistibco/weatherapp:latest
